### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by Diegow3b** [garyzyg/mozjpeg-windows#1]
One README.md would be lovely, trying to run that, but im not familiar with Windows

**Comment by garyzyg** [comment]
Hi @Diegow3b ,

Understand. This project provides unofficial Windows binary release by CI solution Appveyor since official project doesn't. There is no much complex thing, and that's why I intend not to take time on document e.g. README.md.

I may close this suggestion by above reason. Just let me know your idea.

Gary

**Comment by garyzyg** [comment]
Closed by [comment](https://github.com/garyzyg/mozjpeg-windows/issues/1#issuecomment-453939382).
